# Generated by Django 2.2.6 on 2019-11-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20191103_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='', height_field=500, upload_to='', width_field=477),
            preserve_default=False,
        ),
    ]
