# Generated by Django 3.0.2 on 2020-01-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='row_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
